---
title: "StimuliGeneration"
author: "Alex Kale"
date: "6/18/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(gganimate)
library(RColorBrewer)
library(gridExtra)
library(grid)
```

This file contains code to generate stimuli for our effect size judgment and decision-making experiment.

##Data Conditions

```{r}
# linear sampling of log odds for ground truth probability of superiority for the new machine
logodds <- seq(log(0.025/(1-0.025)), log(0.975/(1-0.975)), length.out = 24) 
p_sup <- 1 / (1 + exp(-logodds))

# baseline probability of gaining/keeping a contract with the old machine 
base <- c(.15, .5, .85)

# initialize data conditions dataframe
conds_df <- data.frame(
  "p_superiority" = rep(p_sup, length(base)),
  "baseline" = sort(rep(base, length(p_sup))))
  
# ratio (K) of value of contract (X) over cost of intervention (C)
conds_df <- conds_df %>%
  mutate(K = if_else(baseline == .15, # set K (cost of new machine in millions) contingent on baseline,
                     1.8,             # so there are an equal number of trials where participants should vs shouldn't intervene
                     if_else(baseline == .5,
                             2.25,
                             6.85))) # where baseline == .85

# create df containting rows for practice trials
prac_df <- data.frame(
  "p_superiority" = c(.4, .6),
  "baseline" = c(.95),
  "K" = -1) # placehold, as K will depend on the baseline condition to which a participant is assigned
# append to conditions dataframe
conds_df <- rbind(conds_df, prac_df)

# label gain vs loss framing trials based on p_superiority and add contract thresholds
conds_df <- conds_df %>% 
  mutate(frame = if_else(p_superiority > .5, "gain", "loss"),
                         threshold = if_else(frame=="gain", 
                                             500, # million widgets required to gain contract
                                             75)) # defective widgets per million required to keep contract

# add columns for the mean and standard deviation of the difference in the number of widgets produced by the new vs old machine
# depending on the gain vs loss frame, these values represent millions of widgets vs defective widgets per million
conds_df <- conds_df %>%
  mutate(sd_diff = 15, # std(new - old)
         mean_diff = sd_diff * qnorm(p_superiority)) # mean(new - old)

# double the length of the dataframe to add information per machine, creating a stimulus dataframe with a row per distribution to visualize
conds_df <- map_df(seq_len(2), ~conds_df)
conds_df$Machine <- sort(rep(c("New", "Old"), length(conds_df$p_superiority)/2))

# add columns for the mean and standard deviation of widgets for each machine and the probability of gaining/keeping the contract
conds_df <- conds_df %>%
  mutate(sd = sqrt(conds_df$sd_diff ^ 2 / 2), # assume equal and independent variances in the number of widgets produced by each machine
        mean = if_else(Machine=="Old", 
                       if_else(frame=="gain", # old machine is at baseline
                               threshold - sd * qnorm(1 - baseline), 
                               threshold - sd * qnorm(baseline)), 
                       if_else(frame=="gain", # new machine is at difference from baseline
                               threshold - sd * qnorm(1 - baseline) + mean_diff, 
                               threshold - sd * qnorm(baseline) + mean_diff)),
        p_contract = if_else(frame=="gain", # probability of exceeding threshold to gain/keep contract
                              1 - pnorm((threshold - mean)/sd),
                              pnorm((threshold - mean)/sd)))

# name conditions
conds_df <- conds_df %>%
  rowwise() %>% # need to name each row differently
  mutate(condition = paste(c(baseline, "base", round(p_superiority, 3), "p_sup"), collapse = "_")) %>%
  ungroup() # need to undo rowwise

# for HOPs and quantile dotplots we need to add draws to our dataframe
n <- 1000 # number of samples
n_dots <- 20 # number of dots for quantile dotplots
conds_df$sample_n <- n
conds_df <- conds_df %>% as.tibble() %>%
  mutate(draws = pmap(list(sample_n, mean, sd), rnorm), # get a list of draws from the distribution for each condition
         draw_n = list(seq(1, n)), # number each sample in order to animate multiple views simultaneously
         quantiles = map(draws, ~ quantile(unlist(.x), ppoints(n_dots)))) # use draw to get quantiles
         # leave these draws and quantiles nested in the dataframe for later use since they are not relevant to most visualizations

# save conds_df with the draws used to create these stimuli (for use in analysis)
save(conds_df, file = "stimuli/conds_df.Rda")

# print
head(conds_df)
```

##Visualization Stimuli

We create one of each plot type for each data condition above and save to a folder called stimuli.

```{r echo=FALSE}
# need a color scale for the old and new machines
machines <- as.factor(c("Old","New"))
tColors <- brewer.pal(length(machines), "Set1")
names(tColors) <- levels(machines)
colScale <- scale_colour_manual(values = tColors)
```

```{r echo=FALSE}
# function to draw captions in a consistent location relative to other text
wrap_label <- function(label, char_width) {
  return(lapply(strwrap(label, width = char_width, simplify = FALSE), paste, collapse="\n"))
}
```


```{r}
# select limits for x-axis
data_domain_gain <- c(445, 565)
data_domain_loss <- c(0, 135)

# set plot dimensions
dims_pix <- c(770, 462) # pixel dimensions
ppi <- 75 # assume 75 ppi for the avg monitor
dims <- dims_pix / ppi # dimensions in inches

# HOPs frame rate
frame_rate <- 2.5 
# select number of draws for HOPs conditions
n_draws_hops <- 50

# geom sizes
means_size <- 3
HOPs_size <- 10
HOPs_mean_size_factor <- 1.5
interval_mean_size_factor <- 1.85

# text formating
title_size <- 20
label_size <- 14 
caption_size <- 16
char_before_wrap <- 90

# cycle through rows in the table of data conditions
for (c in unique(conds_df$condition)) {
  # isolaten data for the current condtion
  use_df <- conds_df %>% filter(condition %in% c)
  
  if (all(use_df$frame=="gain")) { # stimuli for gain framing trials
    # means only
    plt <- use_df %>% ggplot(aes(x = mean, y = reorder(Machine, desc(Machine)), color = Machine)) +
      geom_point(size = means_size) +
      theme_bw() +
      colScale +
      xlim(data_domain_gain[1], data_domain_gain[2]) +
      labs(
        title = "Millions of Widgets Produced Per Year",
        x = "Average Number of Widgets Produced (in Millions)",
        y = NULL,
        caption = wrap_label("Dots represent the average number of widgets that could be produced (in millions) by each machine in a given year.", char_before_wrap)) +
      theme(
        axis.title = element_text(size=label_size),
        axis.text.y = element_blank(),
        plot.title = element_text(size = title_size),
        plot.caption = element_text(size = caption_size, hjust = 0, vjust = -1)) +
      geom_vline(xintercept = 500, linetype = "longdash") + # contract threshold
      annotate("text", x = 502, y = 2.4, label = "Above this threshold,\nyou gain the contract.", hjust = 0, vjust = 0)
    fname <- paste("stimuli/means_only-", c,".svg", sep = "")
    ggsave(file = fname, plot = plt, width = dims[1], height = dims[2])
    
    # intervals only
    plt <- use_df %>% ggplot(aes(y = mean, x = reorder(Machine, desc(Machine)), color = Machine)) +
      geom_errorbar(aes(ymin = mean + qnorm(0.025) * sd, ymax = mean + qnorm(0.975) * sd, width = 0)) +
      coord_flip() +
      theme_bw() +
      colScale +
      ylim(data_domain_gain[1], data_domain_gain[2]) +
      labs(
        title = "Millions of Widgets Produced Per Year",
        x = NULL,
        y = "Range of Widgets Produced (in Millions)",
        caption = wrap_label("Intervals contain 95% of the possible numbers of widgets that could be produced (in millions) by each machine in a given year.", char_before_wrap)) +
      theme(
        axis.title = element_text(size=label_size),
        axis.text.y = element_blank(),
        plot.title = element_text(size = title_size),
        plot.caption = element_text(size = caption_size, hjust = 0, vjust = -1)) +
      geom_hline(yintercept = 500, linetype = "longdash") + # contract threshold
      annotate("text", y = 502, x = 2.4, label = "Above this threshold,\nyou gain the contract.", hjust = 0, vjust = 0)
    fname <- paste("stimuli/intervals_only-", c,".svg", sep = "")
    ggsave(file = fname, plot = plt, width = dims[1], height = dims[2])
  
    # hops
    plt <- use_df %>% select(-one_of(c("quantiles"))) %>% unnest() %>%
      filter(draw_n %in% 1:n_draws_hops) %>% # filter to set number of draws
      ggplot(aes(y = draws, x = reorder(Machine, desc(Machine)), color = Machine)) +
      geom_point(shape = 124, size = HOPs_size) +
      coord_flip() +
      theme_bw() +
      colScale +
      ylim(data_domain_gain[1], data_domain_gain[2]) +
      labs(
        title = "Millions of Widgets Produced Per Year",
        y = "Number of Widgets Produced (in Millions)",
        x = NULL,
        caption = wrap_label("Lines represent the number of widgets that could be produced (in millions) by each machine in a given year.", char_before_wrap)) +
      theme(
        axis.title = element_text(size=label_size),
        axis.text.y = element_blank(),
        plot.title = element_text(size = title_size),
        plot.caption = element_text(size = caption_size, hjust = 0, vjust = -1)) +
      geom_hline(yintercept = 500, linetype = "longdash") + # contract threshold
      annotate("text", y = 502, x = 2.4, label = "Above this threshold,\nyou gain the contract.", hjust = 0, vjust = 0) +
      transition_manual(draw_n)
    hops <- animate(plt, fps = 2.5, nframes = 10 * frame_rate, res = 100, width = dims[1]*100, height = dims[2]*100)
    fname <- paste("stimuli/HOPs-", c, ".gif", sep = "")
    anim_save(filename = fname, animation = hops)
  
    # quantile dotplots
    plt <- use_df %>% select(-one_of(c("draws", "draw_n"))) %>% unnest() %>%
      ggplot(aes(x = quantiles, fill = Machine)) +
      geom_dotplot(binwidth = 4, binaxis = "x", dotsize = .9, stackratio = 1.35) +
      theme_bw() +
      scale_fill_brewer(palette = "Set1") +
      facet_grid(Machine ~ .) +
      xlim(data_domain_gain[1], data_domain_gain[2]) +
      ylim(0, .075) +
      labs(
        title = "Millions of Widgets Produced in Previous Years",
        x = "Number of Widgets Produced (in Millions)",
        y = "Possibility of Production",
        caption = wrap_label("Each dot represents 5% of the possible numbers of widgets that could be produced (in millions) by each machine a given year.", char_before_wrap)) +
      theme(
        strip.background = element_blank(),
        strip.text.x = element_blank(),
        axis.title = element_text(size=label_size),
        axis.text.y = element_blank(),
        plot.title = element_text(size = title_size),
        plot.caption = element_text(size = caption_size, hjust = 0, vjust = -1)) +
      geom_vline(xintercept = 500, linetype = "longdash") + # contract threshold
      annotate("text", x = 502, y = .05, label = "Above this threshold,\nyou gain the contract.", hjust = 0, vjust = 0)
    fname <- paste("stimuli/QDPs-", c, ".svg", sep = "")
    ggsave(file = fname, plot = plt, width = dims[1], height = dims[2])
  
    # densities
    plt <- use_df %>% select(-one_of(c("draws", "draw_n"))) %>% unnest() %>%
      ggplot(aes(x = quantiles, fill = Machine)) +
      geom_density() +
      theme_bw() +
      scale_fill_brewer(palette = "Set1") +
      facet_grid(Machine ~ .) +
      xlim(data_domain_gain[1], data_domain_gain[2]) +
      ylim(0, .075) +
      labs(
        title = "Millions of Widgets Produced in Previous Years",
        x = "Number of Widgets Produced (in Millions)",
        y = "Possibility of Production",
        caption = wrap_label("The height of the shape represents the possibility of numbers of widgets that could be produced (in millions) by each machine in a given year.", char_before_wrap)) +
      theme(
        axis.title = element_text(size=label_size),
        axis.text.y = element_blank(),
        plot.title = element_text(size = title_size),
        plot.caption = element_text(size = caption_size, hjust = 0, vjust = -1)) +
      geom_vline(xintercept = 500, linetype = "longdash") + # contract threshold
      annotate("text", x = 502, y = .05, label = "Above this threshold,\nyou gain the contract.", hjust = 0, vjust = 0)
    fname <- paste("stimuli/densities-", c, ".svg", sep = "")
    ggsave(file = fname, plot = plt, width = dims[1], height = dims[2])
  
    # intervals with means
    plt <- use_df %>% ggplot(aes(y = mean, x = reorder(Machine, desc(Machine)), color = Machine)) +
      geom_pointrange(aes(ymin = mean + qnorm(0.025) * sd, ymax = mean + qnorm(0.975) * sd), show.legend = FALSE, fatten = means_size * interval_mean_size_factor) +
      geom_line(aes(y = mean - 1000)) + geom_point(aes(y = mean - 1000)) + # hack to get legend symbols oriented properly
      coord_flip() +
      theme_bw() +
      colScale +
      ylim(data_domain_gain[1], data_domain_gain[2]) +
      labs(
        title="Millions of Widgets Produced in Previous Years",
        y = "Number of Widgets Produced (in Millions)",
        x = NULL,
        caption = wrap_label("Dots represent the average number of widgets that could be produced (in millions) by each machine in a given year, and intervals contain 95% of the possible numbers of widgets that could be produced (in millions) in a given year.", char_before_wrap)) +
      theme(
        axis.title = element_text(size=label_size),
        axis.text.y = element_blank(),
        plot.title = element_text(size = title_size),
        plot.caption = element_text(size = caption_size, hjust = 0, vjust = -1)) +
      geom_hline(yintercept = 500, color = "gray", linetype = "longdash") + # contract threshold
      annotate("text", y = 502, x = 2.4, label = "Above this threshold,\nyou gain the contract.", hjust = 0, vjust = 0)
    fname <- paste("stimuli/intervals_w_means-", c, ".svg", sep = "")
    ggsave(file = fname, plot = plt, width = dims[1], height = dims[2])
  
    # hops with means
    plt <- use_df %>% select(-one_of(c("quantiles"))) %>% unnest() %>%
      filter(draw_n %in% 1:n_draws_hops) %>% # filter to set number of draws
      ggplot(aes(y = mean, x = reorder(Machine, desc(Machine)), color = Machine)) +
      geom_point(size = means_size * HOPs_mean_size_factor) +
      geom_point(aes(y = draws), shape = 124, size = HOPs_size) +
      coord_flip() +
      theme_bw() +
      colScale +
      ylim(data_domain_gain[1], data_domain_gain[2]) +
      labs(
        title = "Millions of Widgets Produced in Previous Years",
        y = "Number of Widgets Produced (in Millions)",
        x = NULL,
        caption = wrap_label("Dots represent the average number of widgets that could be produced (in millions) by each machine in a given year, and lines represent the number of widgets that could produced (in millions) in a given year.", char_before_wrap)) +
      theme(
        axis.title = element_text(size=label_size),
        axis.text.y = element_blank(),
        plot.title = element_text(size = title_size),
        plot.caption = element_text(size = caption_size, hjust = 0, vjust = -1)) +
      geom_hline(yintercept = 500, color = "gray", linetype = "longdash") + # contract threshold
      annotate("text", y = 502, x = 2.4, label = "Above this threshold,\nyou gain the contract.", hjust = 0, vjust = 0) +
      transition_manual(draw_n)
    hops <- animate(plt, fps = 2.5, nframes = 10 * frame_rate, res = 100, width = dims[1]*100, height = dims[2]*100)
    fname <- paste("stimuli/HOPs_w_means-", c, ".gif", sep = "")
    anim_save(filename = fname, animation = hops)
    
  } else { # stimuli for loss framing trials
    # means only
    plt <- use_df %>% ggplot(aes(x = mean, y = reorder(Machine, desc(Machine)), color = Machine)) +
      geom_point(size = means_size) +
      theme_bw() +
      colScale +
      xlim(data_domain_loss[1], data_domain_loss[2]) +
      labs(
        title = "Defective Widgets per Million Produced in Previous Years",
        x = "Average Number of Defective Widgets per Million Produced",
        y = NULL,
        caption = wrap_label("Dots represent the average number of defective widgets per million that could be produced by each machine in a given year.", char_before_wrap)) +
      theme(
        axis.title = element_text(size=label_size),
        axis.text.y = element_blank(),
        plot.title = element_text(size = title_size),
        plot.caption = element_text(size = caption_size, hjust = 0, vjust = -1)) +
      geom_vline(xintercept = 75, linetype = "longdash") + # contract threshold
      annotate("text", x = 49, y = 2.4, label = "Below this threshold,\nyou lose the contract.", hjust = 0, vjust = 0)
    fname <- paste("stimuli/means_only-", c,".svg", sep = "")
    ggsave(file = fname, plot = plt, width = dims[1], height = dims[2])
    
    # intervals only
    plt <- use_df %>% ggplot(aes(y = mean, x = reorder(Machine, desc(Machine)), color = Machine)) +
      geom_errorbar(aes(ymin = mean + qnorm(0.025) * sd, ymax = mean + qnorm(0.975) * sd, width = 0)) +
      coord_flip() +
      theme_bw() +
      colScale +
      ylim(data_domain_loss[1], data_domain_loss[2]) +
      labs(
        title = "Defective Widgets per Million Produced in Previous Years",
        x = NULL,
        y = "Range of Defective Widgets per Million Produced",
        caption = wrap_label("Intervals contain 95% of the possible numbers of defective widgets per million that could be produced by each machine in a given year.", char_before_wrap)) +
      theme(
        axis.title = element_text(size=label_size),
        axis.text.y = element_blank(),
        plot.title = element_text(size = title_size),
        plot.caption = element_text(size = caption_size, hjust = 0, vjust = -1)) +
      geom_hline(yintercept = 75, linetype = "longdash") + # contract threshold
      annotate("text", y = 49, x = 2.4, label = "Below this threshold,\nyou lose the contract.", hjust = 0, vjust = 0)
    fname <- paste("stimuli/intervals_only-", c, ".svg", sep = "")
    ggsave(file = fname, plot = plt, width = dims[1], height = dims[2])
  
    # hops
    plt <- use_df %>% select(-one_of(c("quantiles"))) %>% unnest() %>%
      filter(draw_n %in% 1:n_draws_hops) %>% # filter to set number of draws
      ggplot(aes(y = draws, x = reorder(Machine, desc(Machine)), color = Machine)) +
      geom_point(shape = 124, size = HOPs_size) +
      coord_flip() +
      theme_bw() +
      colScale +
      ylim(data_domain_loss[1], data_domain_loss[2]) +
      labs(
        title = "Defective Widgets per Million Produced in Previous Years",
        y = "Number of Defective Widgets per Million Produced",
        x = NULL,
        caption = wrap_label("Lines represent the number of defective widgets per million that could be produced by each machine in a given year.", char_before_wrap)) +
      theme(
        axis.title = element_text(size=label_size),
        axis.text.y = element_blank(),
        plot.title = element_text(size = title_size),
        plot.caption = element_text(size = caption_size, hjust = 0, vjust = -1)) +
      geom_hline(yintercept = 75, linetype = "longdash") + # contract threshold
      annotate("text", y = 49, x = 2.4, label = "Below this threshold,\nyou lose the contract.", hjust = 0, vjust = 0) +
      transition_manual(draw_n)
    hops <- animate(plt, fps = 2.5, nframes = 10 * frame_rate, res = 100, width = dims[1]*100, height = dims[2]*100)
    fname <- paste("stimuli/HOPs-", c, ".gif", sep = "")
    anim_save(filename = fname, animation = hops)
  
    # quantile dotplots
    plt <- use_df %>% select(-one_of(c("draws", "draw_n"))) %>% unnest() %>%
      ggplot(aes(x = quantiles, fill = Machine)) +
      geom_dotplot(binwidth = 4, binaxis = "x", dotsize = .9, stackratio = 1.35) +
      theme_bw() +
      scale_fill_brewer(palette = "Set1") +
      facet_grid(Machine ~ .) +
      xlim(data_domain_loss[1], data_domain_loss[2]) +
      ylim(0, .075) +
      labs(
        title = "Defective Widgets per Million Produced in Previous Years",
        x = "Number of Defective Widgets per Million Produced",
        y = "Possibility of Production",
        caption = wrap_label("Each dot represents 5% of the possible numbers of defective widgets per million that could be produced by each machine in a given year.", char_before_wrap)) +
      theme(
        strip.background = element_blank(),
        strip.text.x = element_blank(),
        axis.title = element_text(size=label_size),
        axis.text.y = element_blank(),
        plot.title = element_text(size = title_size),
        plot.caption = element_text(size = caption_size, hjust = 0, vjust = -1)) +
      geom_vline(xintercept = 75, linetype = "longdash") + # contract threshold
      annotate("text", x = 49, y = .05, label = "Below this threshold,\nyou lose the contract.", hjust = 0, vjust = 0)
    fname <- paste("stimuli/QDPs-", c, ".svg", sep = "")
    ggsave(file = fname, plot = plt, width = dims[1], height = dims[2])
  
    # densities
    plt <- use_df %>% select(-one_of(c("draws", "draw_n"))) %>% unnest() %>%
      ggplot(aes(x = quantiles, fill = Machine)) +
      geom_density() +
      theme_bw() +
      scale_fill_brewer(palette = "Set1") +
      facet_grid(Machine ~ .) +
      xlim(data_domain_loss[1], data_domain_loss[2]) +
      ylim(0, .075) +
      labs(
        title = "Defective Widgets per Million Produced in Previous Years",
        x = "Number of Defective Widgets per Million Produced",
        y = "Possibility of Production",
        caption = wrap_label("The height of the shape represents the possibility of numbers of defective widgets per million that could be produced by each machine in a given year.", char_before_wrap)) +
      theme(
        axis.title = element_text(size=label_size),
        axis.text.y = element_blank(),
        plot.title = element_text(size = title_size),
        plot.caption = element_text(size = caption_size, hjust = 0, vjust = -1)) +
      geom_vline(xintercept = 75, linetype = "longdash") + # contract threshold
      annotate("text", x = 49, y = .05, label = "Below this threshold,\nyou lose the contract.", hjust = 0, vjust = 0)
    fname <- paste("stimuli/densities-", c, ".svg", sep = "")
    ggsave(file = fname, plot = plt, width = dims[1], height = dims[2])
  
    # intervals with means
    plt <- use_df %>% ggplot(aes(y = mean, x = reorder(Machine, desc(Machine)), color = Machine)) +
      geom_pointrange(aes(ymin = mean + qnorm(0.025) * sd, ymax = mean + qnorm(0.975) * sd), show.legend = FALSE, fatten = means_size * interval_mean_size_factor) +
      geom_line(aes(y = mean - 1000)) + geom_point(aes(y = mean - 1000)) + # hack to get legend symbols oriented properly
      coord_flip() +
      theme_bw() +
      colScale +
      ylim(data_domain_loss[1], data_domain_loss[2]) +
      labs(
        title = "Defective Widgets per Million Produced in Previous Years",
        y = "Number of Defective Widgets per Million Produced",
        x = NULL,
        caption = wrap_label("Dots represent the average number of defective widgets per million that could be produced by each machine in a given year, and intervals contain 95% of the possible numbers of defective widgets per million that could be produced in a given year.", char_before_wrap)) +
      theme(
        axis.title = element_text(size=label_size),
        axis.text.y = element_blank(),
        plot.title = element_text(size = title_size),
        plot.caption = element_text(size = caption_size, hjust = 0, vjust = -1)) +
      geom_hline(yintercept = 75, linetype = "longdash") + # contract threshold
      annotate("text", y = 49, x = 2.4, label = "Below this threshold,\nyou lose the contract.", hjust = 0, vjust = 0)
    fname <- paste("stimuli/intervals_w_means-", c, ".svg", sep = "")
    ggsave(file = fname, plot = plt, width = dims[1], height = dims[2])
  
    # hops with means
    plt <- use_df %>% select(-one_of(c("quantiles"))) %>% unnest() %>%
      filter(draw_n %in% 1:n_draws_hops) %>% # filter to set number of draws
      ggplot(aes(y = mean, x = reorder(Machine, desc(Machine)), color = Machine)) +
      geom_point(size = means_size * HOPs_mean_size_factor) +
      geom_point(aes(y = draws), shape = 124, size = HOPs_size) +
      coord_flip() +
      theme_bw() +
      colScale +
      ylim(data_domain_loss[1], data_domain_loss[2]) +
      labs(
        title = "Defective Widgets per Million Produced in Previous Years",
        y = "Number of Defective Widgets per Million Produced",
        x = NULL,
        caption = wrap_label("Dots represent the average number of defective widgets per million that could be produced by each machine in a given year, and lines represent number of defective widgets per million that could be produced in a given year.", char_before_wrap)) +
      theme(
        axis.title = element_text(size=label_size),
        axis.text.y = element_blank(),
        plot.title = element_text(size = title_size),
        plot.caption = element_text(size = caption_size, hjust = 0, vjust = -1)) +
      geom_hline(yintercept = 75, linetype = "longdash") + # contract threshold
      annotate("text", y = 49, x = 2.4, label = "Below this threshold,\nyou lose the contract.", hjust = 0, vjust = 0) +
      transition_manual(draw_n)
    hops <- animate(plt, fps = 2.5, nframes = 10 * frame_rate, res = 100, width = dims[1]*100, height = dims[2]*100)
    fname <- paste("stimuli/HOPs_w_means-", c, ".gif", sep = "")
    anim_save(filename = fname, animation = hops)
  }
}
```

<!-- ```{r} -->
<!-- # get the mean for the old machine -->
<!-- old_mean <- use_df$mean[use_df$Machine=="Old"] -->

<!-- # difference distribution -->
<!-- use_df %>% ggplot(aes(y = mean_diff, x = "Difference Between Machines (New - Old)")) + -->
<!--       geom_pointrange(aes(ymin = mean_diff + qnorm(0.025) * sd_diff, ymax = mean_diff + qnorm(0.975) * sd_diff), show.legend = FALSE, fatten = means_size * interval_mean_size_factor) + -->
<!--       # geom_line(aes(y = mean_diff - 1000)) + geom_point(aes(y = mean_diff - 1000)) + # hack to get legend symbols oriented properly -->
<!--       coord_flip() + -->
<!--       theme_bw() + -->
<!--       # colScale + -->
<!--       ylim(data_domain_gain[1] - old_mean, data_domain_gain[2] - old_mean) + -->
<!--       labs( -->
<!--         title="Difference Between New and Old Machines: Millions of Widgets Produced in Previous Years", -->
<!--         y = "Number of Widgets Produced (in Millions)", -->
<!--         x = NULL, -->
<!--         caption = wrap_label("Dots represent the average difference in the number of widgets produced (in millions) by each machine in previous years, and intervals represent the span of widgets produced in 95% of previous years.", char_before_wrap)) + -->
<!--       theme( -->
<!--         plot.title = element_text(size = title_size), -->
<!--         plot.caption = element_text(size = caption_size, hjust = 0)) + -->
<!--       geom_hline(yintercept = (500 - old_mean), color = "gray", linetype = "longdash") + # contract threshold -->
<!--       geom_text(aes(y = 500 - old_mean, x = 1, label = "Above this threshold,\nyou gain the contract."), color = "gray", hjust=0, vjust=0, nudge_x = .4, nudge_y = 2) -->
<!-- ``` -->